### ISSUE TITLE
Mod file size

### ISSUE THREAD

**Issue by MrKashew** [CreeperEntertain/CE-s-Minerals-More#1]
mod seems to take up an absurd amount of ram and launch time when used in a modpack
file size is larger than any of the ~500 mods I have been adding
I was wondering what is the reason for this as even aoa3 and biome pack mods are of smaller size + optimization

**Comment by CreeperEntertain** [comment]
The reason for the large file size is due to the soundtrack added. These are biome specific and high quality, and thus use a lot of space. Also see any of the mod pages at the bottom, where the soundtrack is linked.
In terms of generation, I am not sure, but many of the biomes have features where underground materials replace most of the stone underground. This is done by using the ore distribution system with large veins that get placed often. Since this mod comes with a larger amount of materials and resources that all have their unique ore distributions and spawning conditions, this is most likely the cause.
