### ISSUE TITLE
many recipes dont show in JEI or REI

### ISSUE THREAD

**Issue by sprocketaudio** [CreeperEntertain/CE-s-Minerals-More#3]
It seems many recipes dont show in JEI or REI - for example pure carbon, made from coal in the pressurizer. This mod is relatively complicated and I thin its very important to have this.

**Comment by CreeperEntertain** [comment]
As explained in the other report, the mod has its own system of showing recipes, and JEI will be added in the future. The next update will feature a button on the GUIs that brings you to the recipe pages directly.

Thanks for reporting. Since JEI integration is planned for later on, I will close this issue for now. There's only the option to close it as fixed or not planned. I will choose the latter which fits more, but know it's still planned!
